# Do not modify this file!  It was generated by 
# ‘nixos-generate-config’ and may be overwritten 
# by future invocations.  Please make changes to 
# /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{ imports =
    [ (modulesPath + 
    "/installer/scan/not-detected.nix")
	./thinkpad.nix ];

  boot.initrd.availableKernelModules = [ 
  "xhci_pci" "nvme" "usb_storage" "uas" "sd_mod" 
  ]; boot.initrd.kernelModules = [ ]; 
  boot.kernelModules = [ "kvm-intel" ]; 
  boot.extraModulePackages = [ ];

  fileSystems."/" = { device = 
    "/dev/disk/by-uuid/e7736e93-50f1-4059-9128-5018fd4ad303";
      fsType = "btrfs"; options = [ "subvol=@" ];
    };

  fileSystems."/boot" = { device = 
    "/dev/disk/by-uuid/B431-70C2";
      fsType = "vfat"; options = [ "fmask=0077" 
      "dmask=0077" ];
    };

  swapDevices = [ { device = 
    "/dev/disk/by-uuid/9ebae3fc-408c-468f-9617-93670cf13e89"; 
    } ];

  # Enables DHCP on each ethernet and wireless 
  # interface. In case of scripted networking (the 
  # default) this is the recommended approach. 
  # When using systemd-networkd it's still 
  # possible to use this option, but it's 
  # recommended to use it in conjunction with 
  # explicit per-interface declarations with 
  # `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = 
  # lib.mkDefault true; 
  # networking.interfaces.wlp61s0.useDHCP = 
  # lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault 
  "x86_64-linux"; 
  hardware.cpu.intel.updateMicrocode = 
  lib.mkDefault 
  config.hardware.enableRedistributableFirmware;
}
