;;; kakoune-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from kakoune.el

(autoload 'kakoune-setup-keybinds "kakoune" "\
Set up default kakoune keybindings for normal mode.")
(autoload 'kakoune-setup-keybinds-colemak-dh "kakoune" "\
Set up default kakoune keybindings for normal mode colemak-dh
layout to preserve muscle memory.

|--------+---------|
| QWERTY | Colemak |
|--------+---------|
| h      | n       |
| j      | e       |
| k      | i       |
| l      | o       |
| n      | j       |
| e      | k       |
| i      | l       |
| o      | h       |
|--------+---------|
")


;;; Generated autoloads from kakoune-exchange.el

(register-definition-prefixes "kakoune-exchange" '("kakoune-exchange"))


;;; Generated autoloads from kakoune-shell-commands.el

(register-definition-prefixes "kakoune-shell-commands" '("kakoune-shell-"))


;;; Generated autoloads from kakoune-unimpaired.el

(register-definition-prefixes "kakoune-unimpaired" '("kakoune-"))


;;; Generated autoloads from kakoune-utils.el

(register-definition-prefixes "kakoune-utils" '("kakoune-" "mc/split-region"))

;;; End of scraped data

(provide 'kakoune-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; kakoune-autoloads.el ends here
