;;; org-edit-latex-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-edit-latex.el

(autoload 'org-edit-latex-mode "org-edit-latex" "\
LaTeX editing in org mode.

This is a minor mode.  If called interactively, toggle the
`Org-Edit-LaTeX mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `org-edit-latex-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(autoload 'org-edit-latex-preview-at-point "org-edit-latex" "\
Preview LaTeX at point in the edit buffer." t)
(autoload 'org-edit-latex-create-master-maybe "org-edit-latex" "\
Create master file based on value of variable `org-edit-latex-create-master'.

Its value should be one of the following cases:

'overwrite:    when master file already exists, overwrite it.
'ask:          will ask first before creating master file.
other non-nil: when master doesn't exist, create one.
nil:           do not create master file.
")
(autoload 'org-edit-latex-update-master "org-edit-latex" "\
Update TeX-master file.

This function should be called whenever you change the latex
header." t)
(register-definition-prefixes "org-edit-latex" '("org-edit-latex-"))

;;; End of scraped data

(provide 'org-edit-latex-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-edit-latex-autoloads.el ends here
